"""
test_identity_default_v285.py — v2.85 Ed25519 Identity Default-On

Test IDs: ID-01..ID-10, PBC-01..PBC-10
Total: 20 tests

v2.85 changes:
  - Ed25519 keypair is auto-generated by default (no --identity flag required)
  - --no-identity flag disables identity for testing/embedded scenarios
  - AgentCard: capabilities.identity_default=True when identity is loaded
  - GET /protocol-binding/compatibility — multi-protocol compat matrix (6 entries)
"""

import json
import os
import sys
import subprocess
import time
import urllib.request
import urllib.error
import socket
import pytest

# ── helpers ──────────────────────────────────────────────────────────────────

RELAY = os.path.join(os.path.dirname(__file__), "..", "relay", "acp_relay.py")


def _free_port() -> int:
    with socket.socket() as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _http(http_port: int, path: str, method: str = "GET", body=None, timeout: int = 10):
    """HTTP helper using urllib (handles 4xx/5xx via HTTPError)."""
    url = f"http://127.0.0.1:{http_port}{path}"
    data = json.dumps(body).encode() if body is not None else None
    headers = {"Content-Type": "application/json"} if data else {}
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return json.loads(r.read()), r.status
    except urllib.error.HTTPError as e:
        try:
            return json.loads(e.read()), e.code
        except Exception:
            return {}, e.code
    except Exception as exc:
        raise RuntimeError(f"HTTP {method} {path} failed: {exc}") from exc


def _get(http_port: int, path: str):
    """Returns (status_code, body_dict)."""
    body, status = _http(http_port, path, "GET")
    return status, body


def _post(http_port: int, path: str, payload: dict):
    """Returns (status_code, body_dict)."""
    body, status = _http(http_port, path, "POST", payload)
    return status, body


def _wait_for(fn, timeout=15, interval=0.3):
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            if fn():
                return True
        except Exception:
            pass
        time.sleep(interval)
    return False


class _Relay:
    """Context manager: spin up acp_relay.py, yield http_port, teardown.

    acp_relay.py uses:
      --port N   → WebSocket port N
      HTTP API   → port N + 100
    """

    def __init__(self, extra_args=None, identity_file=None):
        self.extra_args = extra_args or []
        self.identity_file = identity_file
        self.ws_port = _free_port()
        self.http_port = self.ws_port + 100
        self.proc = None

    def __enter__(self):
        cmd = [
            sys.executable, RELAY,
            "--port", str(self.ws_port),
            "--local-only",
        ] + self.extra_args
        if self.identity_file:
            cmd += ["--identity", self.identity_file]
        self.proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        )
        def _is_ready():
            try:
                status, body = _get(self.http_port, "/status")
                return status in (200, 204)
            except Exception:
                return False

        ready = _wait_for(_is_ready, timeout=20, interval=0.4)
        if not ready:
            self.proc.kill()
            out, err = self.proc.communicate()
            raise RuntimeError(
                f"Relay did not start on HTTP port {self.http_port}. "
                f"stderr: {err.decode()[-500:]}"
            )
        return self.http_port

    def __exit__(self, *_):
        if self.proc:
            self.proc.terminate()
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill()


# ── ID-01..ID-10: Ed25519 identity default-on ────────────────────────────────

class TestIdentityDefault:
    """ID-01..ID-10: relay auto-generates Ed25519 identity without --identity flag."""

    def test_id01_version_v285(self, tmp_path):
        """ID-01: VERSION is 2.85.0 (in self.acp_version or /status)."""
        with _Relay() as port:
            status, body = _get(port, "/.well-known/acp.json")
            assert status == 200
            # version may be in body["self"]["acp_version"] or body["version"]
            ver = (body.get("version") or
                   body.get("self", {}).get("acp_version") or "")
            assert ver.startswith("2.85"), \
                f"Expected v2.85.x, got '{ver}'. Full body keys: {list(body.keys())}"

    def test_id02_agentcard_identity_default_capability(self, tmp_path):
        """ID-02: AgentCard capabilities.identity_default=True when identity auto-loaded."""
        with _Relay() as port:
            _, body = _get(port, "/.well-known/acp.json")
            caps = body.get("self", body).get("capabilities", {})
            # identity_default should be True when cryptography is available
            # (may be False/absent if cryptography not installed — acceptable)
            if caps.get("identity_default") is not None:
                assert isinstance(caps["identity_default"], bool)

    def test_id03_did_json_available_by_default(self, tmp_path):
        """ID-03: /.well-known/did.json responds 200 without --identity flag."""
        with _Relay() as port:
            status, body = _get(port, "/.well-known/did.json")
            # If cryptography is available: 200 with DID doc
            # If cryptography not available: may be 503 — acceptable
            assert status in (200, 503), f"Unexpected status {status}: {body}"
            if status == 200:
                assert "id" in body or "@context" in body, \
                    "DID document missing 'id' or '@context'"

    def test_id04_jwks_available_by_default(self, tmp_path):
        """ID-04: /.well-known/jwks.json responds 200 without --identity flag."""
        with _Relay() as port:
            status, body = _get(port, "/.well-known/jwks.json")
            assert status == 200
            assert "keys" in body, "JWKS response missing 'keys' field"
            assert isinstance(body["keys"], list)

    def test_id05_agentcard_has_identity_field_by_default(self, tmp_path):
        """ID-05: AgentCard 'identity' field is present in self block without --identity flag."""
        with _Relay() as port:
            _, body = _get(port, "/.well-known/acp.json")
            card = body.get("self", body)
            # identity field should exist (may be 'none' if cryptography unavailable)
            assert "identity" in card, \
                f"AgentCard missing 'identity' field. Keys: {list(card.keys())}"

    def test_id06_no_identity_flag_disables_auto_gen(self, tmp_path):
        """ID-06: --no-identity flag disables automatic Ed25519 generation."""
        with _Relay(extra_args=["--no-identity"]) as port:
            _, body = _get(port, "/.well-known/acp.json")
            caps = body.get("self", body).get("capabilities", {})
            # identity_default should be False or absent when --no-identity is set
            assert not caps.get("identity_default", False), \
                "identity_default should be False with --no-identity"

    def test_id07_no_identity_did_json_returns_error(self, tmp_path):
        """ID-07: /.well-known/did.json returns 4xx/5xx when --no-identity is set."""
        with _Relay(extra_args=["--no-identity"]) as port:
            status, body = _get(port, "/.well-known/did.json")
            # Without identity: 503 (cryptography available but disabled), or 200 with error field
            # Accept any non-200 or 200 with error
            if status == 200:
                # If still 200, should indicate no identity
                assert body.get("error") or not body.get("id"), \
                    f"Expected error when --no-identity, got full DID doc: {body}"

    def test_id08_identity_flag_still_works(self, tmp_path):
        """ID-08: explicit --identity path still works (backward compat)."""
        identity_file = str(tmp_path / "custom_identity.json")
        with _Relay(identity_file=identity_file) as port:
            status, body = _get(port, "/.well-known/acp.json")
            assert status == 200
            card = body.get("self", body)
            # Should have loaded/generated keypair at custom path or relay started cleanly
            assert "capabilities" in card, \
                f"AgentCard missing capabilities. Keys: {list(card.keys())}"

    def test_id09_agentcard_endpoints_include_did_key(self, tmp_path):
        """ID-09: AgentCard endpoints.did_key present when identity default-on."""
        with _Relay() as port:
            _, body = _get(port, "/.well-known/acp.json")
            card = body.get("self", body)
            endpoints = card.get("endpoints", {})
            caps = card.get("capabilities", {})
            # did_key endpoint should be declared if identity auto-loaded
            # (may be absent if cryptography package unavailable)
            if caps.get("identity_default"):
                assert "did_key" in endpoints, \
                    "AgentCard endpoints.did_key missing when identity_default=True"

    def test_id10_get_identity_did_key_endpoint(self, tmp_path):
        """ID-10: GET /identity/did-key returns 200 with did:key when identity default-on."""
        with _Relay() as port:
            status, body = _get(port, "/identity/did-key")
            # 200 if cryptography available, 503 otherwise
            assert status in (200, 503), f"Unexpected status: {status}"
            if status == 200:
                assert body.get("ok") is True
                assert "did_key" in body or "did" in body, \
                    "Response missing did_key/did field"


# ── PBC-01..PBC-10: GET /protocol-binding/compatibility ──────────────────────

class TestProtocolBindingCompatibility:
    """PBC-01..PBC-10: GET /protocol-binding/compatibility — multi-protocol compat matrix."""

    def test_pbc01_returns_200(self, tmp_path):
        """PBC-01: GET /protocol-binding/compatibility returns 200."""
        with _Relay() as port:
            status, body = _get(port, "/protocol-binding/compatibility")
            assert status == 200, f"Expected 200, got {status}: {body}"

    def test_pbc02_ok_true(self, tmp_path):
        """PBC-02: Response body has ok=True."""
        with _Relay() as port:
            _, body = _get(port, "/protocol-binding/compatibility")
            assert body.get("ok") is True

    def test_pbc03_version_field(self, tmp_path):
        """PBC-03: Response includes version field."""
        with _Relay() as port:
            _, body = _get(port, "/protocol-binding/compatibility")
            assert "version" in body
            assert body["version"].startswith("2.85")

    def test_pbc04_compatibility_is_list(self, tmp_path):
        """PBC-04: compatibility field is a non-empty list."""
        with _Relay() as port:
            _, body = _get(port, "/protocol-binding/compatibility")
            assert isinstance(body.get("compatibility"), list)
            assert len(body["compatibility"]) > 0

    def test_pbc05_websocket_native(self, tmp_path):
        """PBC-05: WebSocket listed as 'native' compatibility."""
        with _Relay() as port:
            _, body = _get(port, "/protocol-binding/compatibility")
            compat = {e["protocol"]: e for e in body.get("compatibility", [])}
            assert "websocket" in compat, "websocket entry missing"
            assert compat["websocket"]["level"] == "native"

    def test_pbc06_http_sse_native(self, tmp_path):
        """PBC-06: http/sse listed as 'native' compatibility."""
        with _Relay() as port:
            _, body = _get(port, "/protocol-binding/compatibility")
            compat = {e["protocol"]: e for e in body.get("compatibility", [])}
            assert "http/sse" in compat, "http/sse entry missing"
            assert compat["http/sse"]["level"] == "native"

    def test_pbc07_a2a_partial(self, tmp_path):
        """PBC-07: A2A listed as 'partial' compatibility with aligned_sections."""
        with _Relay() as port:
            _, body = _get(port, "/protocol-binding/compatibility")
            compat = {e["protocol"]: e for e in body.get("compatibility", [])}
            assert "a2a" in compat, "a2a entry missing"
            assert compat["a2a"]["level"] == "partial"
            assert "aligned_sections" in compat["a2a"]

    def test_pbc08_grpc_none(self, tmp_path):
        """PBC-08: gRPC listed as 'none' (ACP design constraint)."""
        with _Relay() as port:
            _, body = _get(port, "/protocol-binding/compatibility")
            compat = {e["protocol"]: e for e in body.get("compatibility", [])}
            assert "grpc" in compat, "grpc entry missing"
            assert compat["grpc"]["level"] == "none"

    def test_pbc09_post_returns_405(self, tmp_path):
        """PBC-09: POST /protocol-binding/compatibility returns 405."""
        with _Relay() as port:
            status, body = _post(port, "/protocol-binding/compatibility", {})
            assert status == 405, f"Expected 405, got {status}"

    def test_pbc10_acp_binding_uri_present(self, tmp_path):
        """PBC-10: Response includes acp_binding URI field."""
        with _Relay() as port:
            _, body = _get(port, "/protocol-binding/compatibility")
            assert "acp_binding" in body
            assert "acp" in body["acp_binding"].lower() or "urn:" in body["acp_binding"]
